// Package sdk routes model-produced JSON requests to a mymcp server.
package sdk

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/phillip-england/mymcp/internal/protocol"
)

const sandboxHeader = protocol.SandboxHeader

// Response contains the complete response returned by the mymcp server.
// Non-2xx HTTP responses are returned here rather than converted into SDK errors.
type Response struct {
	StatusCode int
	Header     http.Header
	Body       []byte
}

// Text returns the response body as a string.
func (r *Response) Text() string {
	return string(r.Body)
}

// Client sends validated JSON requests to one mymcp server. Sandbox is supplied
// by the harness and overrides any sandbox header generated by the model.
type Client struct {
	baseURL    *url.URL
	sandbox    string
	httpClient *http.Client
}

// NewClient constructs an SDK client. The sandbox may be empty only when the
// client will call / or /map; filesystem tools require a configured sandbox.
func NewClient(baseURL, sandbox string) (*Client, error) {
	parsed, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("parse base URL: %w", err)
	}
	if (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return nil, errors.New("base URL must be an absolute HTTP or HTTPS URL")
	}
	if parsed.RawQuery != "" || parsed.Fragment != "" || (parsed.Path != "" && parsed.Path != "/") {
		return nil, errors.New("base URL must not contain a path, query, or fragment")
	}
	parsed.Path = ""
	return &Client{baseURL: parsed, sandbox: sandbox, httpClient: http.DefaultClient}, nil
}

// WithHTTPClient replaces the HTTP transport used by the client. A nil value
// restores http.DefaultClient.
func (c *Client) WithHTTPClient(client *http.Client) *Client {
	if client == nil {
		client = http.DefaultClient
	}
	c.httpClient = client
	return c
}

// RouteJSON validates a model-produced JSON request, maps it to a known mymcp
// endpoint, sends it, and returns the server response.
func (c *Client) RouteJSON(ctx context.Context, payload []byte) (*Response, error) {
	requestSpec, target, err := decodeAndRoute(payload)
	if err != nil {
		return nil, err
	}
	if strings.HasPrefix(target.Path, "/tool/") && strings.TrimSpace(c.sandbox) == "" {
		return nil, errors.New("filesystem tool request requires an SDK sandbox")
	}

	destination := c.baseURL.ResolveReference(target)
	request, err := http.NewRequestWithContext(ctx, requestSpec.Method, destination.String(), strings.NewReader(requestSpec.Body))
	if err != nil {
		return nil, fmt.Errorf("build HTTP request: %w", err)
	}
	for name, value := range requestSpec.Headers {
		request.Header.Set(name, value)
	}
	if strings.HasPrefix(target.Path, "/tool/") {
		request.Header.Set(sandboxHeader, c.sandbox)
	}

	httpClient := c.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	httpResponse, err := httpClient.Do(request)
	if err != nil {
		return nil, fmt.Errorf("send mymcp request: %w", err)
	}
	defer httpResponse.Body.Close()
	body, err := io.ReadAll(httpResponse.Body)
	if err != nil {
		return nil, fmt.Errorf("read mymcp response: %w", err)
	}
	return &Response{StatusCode: httpResponse.StatusCode, Header: httpResponse.Header.Clone(), Body: body}, nil
}
